name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. checkout
      - uses: actions/checkout@v3

      # 2. Java 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. properties 설정
      - name: Set up application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION }}" > src/main/resources/application.yml

      # 4. gradlew 실행 권한 설정
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      # 5. gradlew build
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build